THE_GHOME_SHELL_THEME_NAME="Fluent-round-Dark"
THE_WM_THEME_NAME="Fluent-round-Dark"
THE_GTK_THEME_NAME="Fluent-round-Dark"
THE_ICON_THEME_NAME="Fluent-dark"
THE_CURSOR_THEME_NAME="Fluent-dark-cursors"
THE_CURSOR_SIZE="24"
